name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Build"
        run: ./gradlew build
      - name: "Build Native Image"
        run: ./gradlew nativeImage
      - name: "Upload Native Image"
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/graal/reqover
          asset_name: reqover
          asset_content_type: application/octet-stream
